[package]
name = "madsim-tonic-build"
version = "0.7.2"
edition = "2021"
authors = ["Lucio Franco <luciofranco14@gmail.com>", "Runji Wang <wangrunji0408@163.com>"]
description = "Codegen module of `madsim-tonic` gRPC implementation."
homepage = "https://github.com/madsys-dev/madsim"
repository = "https://github.com/madsys-dev/madsim"
categories = ["network-programming", "asynchronous"]
keywords = ["rpc", "grpc", "async", "codegen", "protobuf"]
readme = "README.md"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prettyplease = "0.1"
proc-macro2 = "1"
prost-build = { version = "0.10", optional = true }
quote = "1"
syn = "1"
tonic-build = "0.7"

[features]
compression = []
default = ["transport", "prost"]
prost = ["prost-build"]
transport = []
